spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: lemoor@mail.ru
  flyway:
    baseline-on-migration: true
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 465
    username: remartvspb@gmail.com
    password: bwivsizunqvdpxbk
    protocol: smtps

