spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: lemoor@mail.ru
  flyway:
    baseline-on-migration: true

